services:
  wordpress:
    networks:
      - agruet
    build: ./requirements/wordpress
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - wordpress_files:/var/www/html

  db:
    networks:
      - agruet
    build: ./requirements/mariadb
    env_file: .env
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql
    tmpfs:
      - /run/mysqld
    healthcheck:
          test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 30s

  nginx:
    networks:
      - agruet
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      db:
        condition: service_healthy
      wordpress:
        condition: service_healthy
    secrets:
      - cert_pem
      - cert_key

volumes:
  db_data:
  wordpress_files:

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  cert_key:
    file: ../secrets/cert.key
  cert_pem:
    file: ../secrets/cert.pem

networks:
  agruet:
