daemon off;

events {}

http {
    server {
        listen  0.0.0.0:443 ssl;
        listen  [::]:443    ssl;
        server_name www.tgallet.42.fr tgallet.42.fr;
        ssl_certificate /run/secrets/cert.pem;
        ssl_certificate_key /run/secrets/cert.key;
        ssl_protocols TLSv1.3;
        index index.php;
        root /var/www/html;
        location ~* [^/]\.php(/|$) {
            try_files $uri =404;
            fastcgi_pass wordpress:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
